version: '3.7'
services:
  wbns_nginx:
    build: docker/nginx
    container_name: wbns_nginx
    ports:
      - "91:80"
    volumes:
      - ./docker/nginx/conf:/etc/nginx/conf.d
      - .:/var/www/html
      - ./docker/nginx/log/:/var/log/nginx
      - /tmp:/tmp
    depends_on:
      - wbns_php
    networks:
      - wbns-net

  wbns_php:
    build: docker/php
    container_name: wbns_php
    volumes:
      - .:/var/www/html
      - /tmp:/tmp
      - ~/.composer:/var/www/.composer
    depends_on:
      - wbns_mysql
    networks:
      - wbns-net

  wbns_mysql:
    image: mysql:5.7
    container_name: wbns_mysql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=wbnsdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    volumes:
      - wbns_mysql_data:/var/lib/mysql
    networks:
      - wbns-net

  wbns_pma:
    image: phpmyadmin/phpmyadmin
    container_name: wbns_pma
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8091:80
    volumes:
     - /sessions
    networks:
      - wbns-net

networks:
  wbns-net:
volumes:
  wbns_mysql_data:
